version: "3"
services:
  tornado-webhook-server:
    container_name: "tornado-webhook-server"
    build: .
    restart: unless-stopped
    environment:
        TZ: Asia/Tokyo
    env_file:
      - tornado_webserver/stack.env
#    volumes:
#      - ${PWD}/tws:/app
    ports:
        - '8001:8080'